---
title: "P8105 Homework 2"
author: "Ruiyang Li"
output: github_document
---

This is my solution to HW2.

```{r setup}
library(readxl)
library(tidyverse)
```

## Problem 1

Read and clean the Mr. Trash Wheel sheet:

```{r}
mr_trash_wheel = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "Mr. Trash Wheel", 
             range = cell_cols("A:N"),
             skip = 1) %>% 
  janitor::clean_names() %>%
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = as.integer(round(sports_balls, 0))
  ) 
```


Read and clean precipitation data for 2017 and 2018:

```{r}
precip_2017 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "2017 Precipitation",
             range = "A2:B14") %>% 
  janitor::clean_names() %>%   
  mutate(year = "2017") %>% 
  relocate(year)
  
precip_2018 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
             sheet = "2018 Precipitation",
             range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  mutate(year = "2018") %>% 
  relocate(year)
```

Combine precipitation datasets:

```{r}
precip = 
  bind_rows(precip_2017, precip_2018) %>% 
  mutate(month = month.name[month])
```




